Implement task 01 - ES6 + Babel + Webpack
ruslanabdraev/FrontCamp pull request #1
Opened 2019-10-29 12:24 UTC by ruslanabdraev

2019-10-30 14:09 UTC, sergey-guk-dev requested changes

2019-10-30 14:09 UTC, eventpromo commented on Task-01-JSCore-ES6-Babel-Webpack/src/articles.js
> +    return items.map(item =>{
Можно вот так написать items.map(article)

2019-10-30 14:09 UTC, eventpromo commented on Task-01-JSCore-ES6-Babel-Webpack/src/index.js
> +fetch("https://newsapi.org/v1/articles?source=bbc-news&apiKey=2ed7982b8edb4e8c8f81f08dfb8889fe")
давай вынесим методы обращения к апи в отдельные сервисы.

2019-10-30 14:09 UTC, eventpromo commented on Task-01-JSCore-ES6-Babel-Webpack/src/article.js
> +const article = (item) =>{
Давай немного изменим структуру файлов и папок. Повыноси компоненты в необходимые папки. В дальнейшем проект будет развиваться.

2019-10-30 18:32 UTC, ruslanabdraev commented on Task-01-JSCore-ES6-Babel-Webpack/src/articles.js
> +    return items.map(item =>{
done

2019-10-30 18:32 UTC, ruslanabdraev commented on Task-01-JSCore-ES6-Babel-Webpack/src/article.js
> +const article = (item) =>{
done

2019-10-30 19:13 UTC, ruslanabdraev commented on Task-01-JSCore-ES6-Babel-Webpack/src/index.js
> +fetch("https://newsapi.org/v1/articles?source=bbc-news&apiKey=2ed7982b8edb4e8c8f81f08dfb8889fe")
done

2019-10-31 11:37 UTC, sergey-guk-dev requested changes

2019-10-31 11:37 UTC, sergey-guk-dev commented on Task-01-JSCore-ES6-Babel-Webpack/src/index.js
> +.then(response => response.json())
перепиши плиз через async

2019-10-31 11:37 UTC, sergey-guk-dev commented on Task-01-JSCore-ES6-Babel-Webpack/src/style.css
> +.detailedNewsContainer{
давай будем стараться придерживаться БЭМ наименований.
https://yandex.ru/dev/bem/

2019-10-31 11:37 UTC, sergey-guk-dev commented on Task-01-JSCore-ES6-Babel-Webpack/webpack.config.js
> +    mode: "development",
попробуй реализовать два конфигурационных файла DEV и RELEASE (например разные ключи для апи) и чтобы была возможность собирать приложение с разной конфигурацией

2019-10-31 11:37 UTC, sergey-guk-dev commented on Task-01-JSCore-ES6-Babel-Webpack/src/index.js
> +    .then(response => response.json())
Сделай, пожалуйста, чтобы getNews() уже возвращал промис с articles

2019-11-03 16:23 UTC, ruslanabdraev commented
Reopen

2019-11-03 16:43 UTC, merged